// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/FirstRes.proto

package com.study.gupao.netty.protobuf.res;

public final class FirstResponse {
  private FirstResponse() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface FirstResOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.study.gupao.netty.protobuf.res.FirstRes)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string resMsg = 1;</code>
     */
    boolean hasResMsg();
    /**
     * <code>optional string resMsg = 1;</code>
     */
    java.lang.String getResMsg();
    /**
     * <code>optional string resMsg = 1;</code>
     */
    com.google.protobuf.ByteString
        getResMsgBytes();
  }
  /**
   * Protobuf type {@code com.study.gupao.netty.protobuf.res.FirstRes}
   */
  public static final class FirstRes extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:com.study.gupao.netty.protobuf.res.FirstRes)
      FirstResOrBuilder {
    // Use FirstRes.newBuilder() to construct.
    private FirstRes(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private FirstRes(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final FirstRes defaultInstance;
    public static FirstRes getDefaultInstance() {
      return defaultInstance;
    }

    public FirstRes getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private FirstRes(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              resMsg_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.study.gupao.netty.protobuf.res.FirstResponse.internal_static_com_study_gupao_netty_protobuf_res_FirstRes_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.study.gupao.netty.protobuf.res.FirstResponse.internal_static_com_study_gupao_netty_protobuf_res_FirstRes_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.study.gupao.netty.protobuf.res.FirstResponse.FirstRes.class, com.study.gupao.netty.protobuf.res.FirstResponse.FirstRes.Builder.class);
    }

    public static com.google.protobuf.Parser<FirstRes> PARSER =
        new com.google.protobuf.AbstractParser<FirstRes>() {
      public FirstRes parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new FirstRes(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<FirstRes> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int RESMSG_FIELD_NUMBER = 1;
    private java.lang.Object resMsg_;
    /**
     * <code>optional string resMsg = 1;</code>
     */
    public boolean hasResMsg() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string resMsg = 1;</code>
     */
    public java.lang.String getResMsg() {
      java.lang.Object ref = resMsg_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          resMsg_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string resMsg = 1;</code>
     */
    public com.google.protobuf.ByteString
        getResMsgBytes() {
      java.lang.Object ref = resMsg_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        resMsg_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      resMsg_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getResMsgBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getResMsgBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.study.gupao.netty.protobuf.res.FirstResponse.FirstRes parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.study.gupao.netty.protobuf.res.FirstResponse.FirstRes parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.study.gupao.netty.protobuf.res.FirstResponse.FirstRes parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.study.gupao.netty.protobuf.res.FirstResponse.FirstRes parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.study.gupao.netty.protobuf.res.FirstResponse.FirstRes parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.study.gupao.netty.protobuf.res.FirstResponse.FirstRes parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.study.gupao.netty.protobuf.res.FirstResponse.FirstRes parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.study.gupao.netty.protobuf.res.FirstResponse.FirstRes parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.study.gupao.netty.protobuf.res.FirstResponse.FirstRes parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.study.gupao.netty.protobuf.res.FirstResponse.FirstRes parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.study.gupao.netty.protobuf.res.FirstResponse.FirstRes prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.study.gupao.netty.protobuf.res.FirstRes}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.study.gupao.netty.protobuf.res.FirstRes)
        com.study.gupao.netty.protobuf.res.FirstResponse.FirstResOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.study.gupao.netty.protobuf.res.FirstResponse.internal_static_com_study_gupao_netty_protobuf_res_FirstRes_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.study.gupao.netty.protobuf.res.FirstResponse.internal_static_com_study_gupao_netty_protobuf_res_FirstRes_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.study.gupao.netty.protobuf.res.FirstResponse.FirstRes.class, com.study.gupao.netty.protobuf.res.FirstResponse.FirstRes.Builder.class);
      }

      // Construct using com.study.gupao.netty.protobuf.res.FirstResponse.FirstRes.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        resMsg_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.study.gupao.netty.protobuf.res.FirstResponse.internal_static_com_study_gupao_netty_protobuf_res_FirstRes_descriptor;
      }

      public com.study.gupao.netty.protobuf.res.FirstResponse.FirstRes getDefaultInstanceForType() {
        return com.study.gupao.netty.protobuf.res.FirstResponse.FirstRes.getDefaultInstance();
      }

      public com.study.gupao.netty.protobuf.res.FirstResponse.FirstRes build() {
        com.study.gupao.netty.protobuf.res.FirstResponse.FirstRes result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.study.gupao.netty.protobuf.res.FirstResponse.FirstRes buildPartial() {
        com.study.gupao.netty.protobuf.res.FirstResponse.FirstRes result = new com.study.gupao.netty.protobuf.res.FirstResponse.FirstRes(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.resMsg_ = resMsg_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.study.gupao.netty.protobuf.res.FirstResponse.FirstRes) {
          return mergeFrom((com.study.gupao.netty.protobuf.res.FirstResponse.FirstRes)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.study.gupao.netty.protobuf.res.FirstResponse.FirstRes other) {
        if (other == com.study.gupao.netty.protobuf.res.FirstResponse.FirstRes.getDefaultInstance()) return this;
        if (other.hasResMsg()) {
          bitField0_ |= 0x00000001;
          resMsg_ = other.resMsg_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.study.gupao.netty.protobuf.res.FirstResponse.FirstRes parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.study.gupao.netty.protobuf.res.FirstResponse.FirstRes) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object resMsg_ = "";
      /**
       * <code>optional string resMsg = 1;</code>
       */
      public boolean hasResMsg() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string resMsg = 1;</code>
       */
      public java.lang.String getResMsg() {
        java.lang.Object ref = resMsg_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            resMsg_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string resMsg = 1;</code>
       */
      public com.google.protobuf.ByteString
          getResMsgBytes() {
        java.lang.Object ref = resMsg_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          resMsg_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string resMsg = 1;</code>
       */
      public Builder setResMsg(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        resMsg_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string resMsg = 1;</code>
       */
      public Builder clearResMsg() {
        bitField0_ = (bitField0_ & ~0x00000001);
        resMsg_ = getDefaultInstance().getResMsg();
        onChanged();
        return this;
      }
      /**
       * <code>optional string resMsg = 1;</code>
       */
      public Builder setResMsgBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        resMsg_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.study.gupao.netty.protobuf.res.FirstRes)
    }

    static {
      defaultInstance = new FirstRes(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.study.gupao.netty.protobuf.res.FirstRes)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_study_gupao_netty_protobuf_res_FirstRes_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_study_gupao_netty_protobuf_res_FirstRes_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024proto/FirstRes.proto\022\"com.study.gupao." +
      "netty.protobuf.res\"\032\n\010FirstRes\022\016\n\006resMsg" +
      "\030\001 \001(\tB\017B\rFirstResponse"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_study_gupao_netty_protobuf_res_FirstRes_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_study_gupao_netty_protobuf_res_FirstRes_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_study_gupao_netty_protobuf_res_FirstRes_descriptor,
        new java.lang.String[] { "ResMsg", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
